### PR TITLE
Update nodejs 12 version

### PR DESCRIPTION
**Pull request by tlbdk**

### CODE REVIEW

**Comment by bfw** [comment]
I can't see the build result here. Is this not set up for the docker-node repository?

**Comment by tlbdk** [comment]
Yes it has, we ran into an issue with the new version of npm breaking the root installation so @mex merged a patch that allows for ssh keys wrapper to work without root, so this patch pull should drop the NPM update before being merged.

**Comment by mex** [comment]
We should probably skip 12.10 for 12.11 as they fixed a performance regression: https://twitter.com/matteocollina/status/1177614894012780544?s=21

But I’m generally more in favor of waiting until LTS.

**Comment by tlbdk** [comment]
I have dropped the npm update in the and bump to newest node 12.x version

**Pull request merged**
